apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: denyall-nextcloud-policy
  namespace: nextcloud
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-policy
  namespace: nextcloud
spec:
  podSelector: 
    matchLabels:
      app: nextcloud
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: go-puller
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ai
      ports:
        - protocol: TCP
          port: 80


---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-mariadb-policy
  namespace: nextcloud
spec:
  podSelector:
    matchLabels:
      app: nextcloud
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mariadb
      ports:
        - protocol: TCP
          port: 3306

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-coredns-policy
  namespace: nextcloud
spec:
  podSelector:
    matchLabels:
      app: nextcloud
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-tailscale-nextcloud-policy
  namespace: nextcloud
spec:
  podSelector:
    matchLabels:
      app: nextcloud
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tailscale
          podSelector:
            matchLabels:
              tailscale.com/managed: "true"
      ports:
        - protocol: TCP
          port: 80