apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    tailscale.com/hostname: nextcloud
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: nextcloud
      port:
        number: 80