apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: ai

spec:
  replicas: 1

  selector:
    matchLabels:
      app: whisper

  template:
    metadata:
      labels:
        app: whisper

    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: whisper
          image: hhector16/whisper-ai:0.1
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: HF_HUB_DISABLE_XET
              value: "1"

            - name: TOKENIZERS_PARALLELISM
              value: "false"

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"

            limits:
              cpu: "2"
              memory: "3Gi"

          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 300
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3