apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-07-30T14:15:53Z"
  labels:
    kubernetes.io/metadata.name: vpn
  name: vpn
  resourceVersion: "14064"
  uid: 9c1194b8-accc-4adc-a774-b892e82fcebb
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
