apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: lscr.io/linuxserver/wireguard:latest
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Europe/Madrid"
          - name: SERVERPORT
            value: "51820"
          - name: PEERS
            value: "portatilHector, movilHector,pcHector"
          - name: PEERDNS
            value: "auto"
        ports:
          - containerPort: 51820
            protocol: UDP
        volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          emptyDir: {}
