apiVersion: batch/v1
kind: CronJob
metadata:
  name: go-puller-cronjob
  namespace: ai
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: go-puller-cronjob
              image: hhector16/go-puller:1.0
              env:
                - name: OLLAMA_AI_ENDPOINT
                  valueFrom:
                    configMapKeyRef:
                      name: go-puller-configmap
                      key: OLLAMA_AI_ENDPOINT

                - name: OLLAMA_AGENT_MODEL
                  valueFrom:
                    configMapKeyRef:
                      name: go-puller-configmap
                      key: OLLAMA_AGENT_MODEL

                - name: OLLAMA_PROMPT_FILE
                  valueFrom:
                    configMapKeyRef:
                      name: go-puller-configmap
                      key: OLLAMA_PROMPT_FILE

                - name: WHISPER_AI_ENDPOINT
                  valueFrom:
                    configMapKeyRef:
                      name: go-puller-configmap
                      key: WHISPER_AI_ENDPOINT

                - name: SCOPED_FOLDER_PATH
                  valueFrom:
                    configMapKeyRef:
                      name: go-puller-configmap
                      key: SCOPED_FOLDER_PATH
                
                - name: NEXT_CLOUD_DOMAIN
                  valueFrom:
                    configMapKeyRef:
                      name: go-puller-configmap
                      key: NEXT_CLOUD_DOMAIN

                - name: NEXTCLOUD_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: go-puller-secret
                      key: NEXTCLOUD_USERNAME

                - name: NEXTCLOUD_PSW
                  valueFrom:
                    secretKeyRef:
                      name: go-puller-secret
                      key: NEXTCLOUD_PSW